name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Blue-Green Deploy
        run: |
          set -e

          IMAGE=ghcr.io/martinhelesic/docker-test:latest

          ACTIVE=$(docker ps --format "{{.Names}}" | grep docker-test || true)

          if [[ "$ACTIVE" == "docker-test-blue" ]]; then
          NEW="docker-test-green"
          OLD="docker-test-blue"
          else
          NEW="docker-test-blue"
          OLD="docker-test-green"
          fi

          echo "Cleaning NEW container"
          docker rm -f $NEW || true

          echo "Pull image"
          docker pull $IMAGE

          echo "Run NEW container on random port"
          docker run -d -p 0:8000 --name $NEW $IMAGE

          PORT=$(docker port $NEW 8000 | cut -d: -f2)

          echo "Testing health..."
          sleep 5

          if curl -f localhost:$PORT/health; then
            echo
            echo "-----------------------------"
            echo -e "\033[32m[OK] Health passed\033[0m"
            echo "-----------------------------"
            echo "Switching nginx..."

            echo "events {} http { server { listen 80; location / { proxy_pass http://172.17.0.1:$PORT; } } }" > ~/nginx.conf

            docker exec nginx-proxy nginx -s reload

            echo "Removing old container..."
            docker rm -f $OLD || true
          else
            echo
            echo "-----------------------------"
            echo -e "\033[31m[ERROR] Health failed\033[0m"
            echo "-----------------------------"
            docker rm -f $NEW
            exit 1
          fi

          echo "New container running on port $PORT"

          sleep 5

          curl localhost:$PORT

          echo ""
          echo "Stopping OLD container"
          docker rm -f $OLD || true

          echo "Running containers:"
          docker ps
