name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Blue-Green Deploy
        run: |
          set -e

          IMAGE=ghcr.io/martinhelesic/docker-test:latest

          # zjisti aktivní container
          ACTIVE=$(docker ps --format "{{.Names}}" | grep docker-test || true)

          if [[ "$ACTIVE" == "docker-test-blue" ]]; then
            NEW="docker-test-green"
            OLD="docker-test-blue"
            PORT=8005
          else
            NEW="docker-test-blue"
            OLD="docker-test-green"
            PORT=8004
          fi

          echo "Active: $ACTIVE"
          echo "Deploying new container: $NEW"

          docker pull $IMAGE

          docker run -d -p $PORT:8000 --name $NEW $IMAGE

          echo "Waiting for app..."
          sleep 5

          curl localhost:$PORT

          echo "Switching traffic..."

          docker stop $OLD || true
          docker rm $OLD || true

          docker ps
