name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Deploy locally on Raspberry
        run: |
          docker pull ghcr.io/martinhelesic/docker-test:latest
          docker stop docker-test-ghcr || true
          docker rm docker-test-ghcr || true
          docker run -d -p 8004:8000 --name docker-test-ghcr ghcr.io/martinhelesic/docker-test:latest
